@startuml

skinparam classAttributeIconSize 0
hide members

package "framework" {
  abstract class ListSearchInfo
  class Pagination extends ListSearchInfo

  class EntityList
  EntityList --> Pagination

  class UniversalDao
  UniversalDao ..> EntityList: <<find>>
}

package listSearchResult {
  hide circle

  class ListSearchResult <<tag>>

  class ListSearchPaging <<tag>>
  ListSearchResult ..> ListSearchPaging: <<use>>

  class ListSearchSubmit <<tag>>
  ListSearchPaging ..> ListSearchSubmit: <<use>>

  class table <<tag>>
  ListSearchResult ..> table: <<use>>
}

ListSearchResult --> EntityList

@enduml