@startuml
!pragma layout smetana
skinparam shadowing false
skinparam defaultFontName "Noto Sans JP"
title リクエスト単体テスト（MOMによるメッセージング・メッセージ受信）の構成
file "テストデータ" as TD
rectangle "テストクラス" as TC
rectangle "サポートクラス\n（MessagingRequestTestSupport、\n応答不要メッセージ受信はサブクラスの\nMessagingReceiveTestSupport）" as SUP
rectangle "テスト用のメインクラス\n（MainForRequestTesting）" as MAIN
rectangle "Nablarch Application Framework" as NAF
rectangle "テスト対象のアプリケーション" as APP
rectangle "DbAccessTestSupport" as DATS
rectangle "MQSupport" as MQS
database "データベース" as DB
queue "キュー" as Q
TD --> SUP
TC --> SUP : インジェクションして\nexecute を呼び出す
SUP --> MAIN : 起動する
MAIN --> NAF : 起動する
NAF --> APP : 実行する
SUP --> DATS : 準備データの投入と結果の確認\n（データベース）
SUP --> MQS : 準備データの投入と結果の確認\n（キュー）
DATS --> DB
MQS --> Q
@enduml
