@startuml

Handler -> DB_Store: 有効期間設定を取得
Handler -> HTTP_Session_Store: 有効期間設定を取得
Handler -> HIDDEN_Store: 有効期間設定を取得
Handler -> Handler: 有効期間を算出
note right: 各ストアからの設定を元に最長の有効期間を算出

Handler -> DB_Store: 保存
note right: 有効期間付きで保存する（有効期間は各ストアで全て同じ値）
        
Handler -> HTTP_Session_Store: 保存
Handler -> HIDDEN_Store: 保存
Handler -> Cookie: セッションID保存

@enduml
