@startuml
!pragma layout smetana
skinparam classAttributeIconSize 0
skinparam shadowing false
skinparam defaultFontName "Noto Sans JP"
hide members
hide circle
title テスティングフレームワークが提供するサポートクラスの継承関係
abstract class TestEventDispatcher
class TestSupport
class DbAccessTestSupport
class EntityTestSupport
class HttpRequestTestSupport
abstract class AbstractHttpRequestTestTemplate
abstract class BasicHttpRequestTestTemplate
abstract class StandaloneTestSupportTemplate
class BatchRequestTestSupport
class MessagingRequestTestSupport
class MessagingReceiveTestSupport
class SimpleRestTestSupport <<nablarch-testing-rest>>
class RestTestSupport <<nablarch-testing-rest>>
TestEventDispatcher <|-- TestSupport
TestEventDispatcher <|-- DbAccessTestSupport
TestEventDispatcher <|-- EntityTestSupport
TestEventDispatcher <|-- HttpRequestTestSupport
TestEventDispatcher <|-- StandaloneTestSupportTemplate
TestEventDispatcher <|-- SimpleRestTestSupport
HttpRequestTestSupport <|-- AbstractHttpRequestTestTemplate
AbstractHttpRequestTestTemplate <|-- BasicHttpRequestTestTemplate
StandaloneTestSupportTemplate <|-- BatchRequestTestSupport
StandaloneTestSupportTemplate <|-- MessagingRequestTestSupport
MessagingRequestTestSupport <|-- MessagingReceiveTestSupport
SimpleRestTestSupport <|-- RestTestSupport
note bottom of BasicHttpRequestTestTemplate : ウェブアプリケーションの\nリクエスト単体テスト
note bottom of RestTestSupport : RESTfulウェブサービスの\nリクエスト単体テスト
note bottom of SimpleRestTestSupport : RESTfulウェブサービスの\nリクエスト単体テスト
note bottom of BatchRequestTestSupport : Nablarchバッチアプリケーションの\nリクエスト単体テスト
note bottom of MessagingRequestTestSupport : 同期応答メッセージ受信の\nリクエスト単体テスト
note bottom of MessagingReceiveTestSupport : 応答不要メッセージ受信の\nリクエスト単体テスト
note bottom of DbAccessTestSupport : コンポーネント単体テスト
note bottom of EntityTestSupport : エンティティ単体テスト
@enduml
